### ISSUE TITLE
Add build dependencies to Conda for GPUCI builds

### ISSUE THREAD

**Issue by vellamike** [clara-genomics/ClaraGenomicsAnalysis#101]
Some recent GPUCI failures have revealed that (eg [this one](https://gpuci.gpuopenanalytics.com/blue/organizations/jenkins/gpuCI-private%2Fclara-genomics-analysis%2Fprb%2Fclara-genomics-analysis-cpu-build/detail/clara-genomics-analysis-cpu-build/1457/pipeline)) have revealed that we are sensitive to what packages are installed on GPUCI VM/docker instances we are running.

Conda should be used as much as possible to allow our tests to run on a clean CI instance. This includes at a minimum:

1. Cmake
2. Flake

**Comment by vellamike** [comment]
@tijyojwad and @vellamike  addressing in #97

**Comment by tijyojwad** [comment]
Thanks for adding the cmake build to the PR! Closing as merged and fixed with #97 .
