### ISSUE TITLE
clang-format: fix member initializer formatting

### ISSUE THREAD

**Issue by tijyojwad** [clara-genomics/ClaraGenomicsAnalysis#114]
clang-format formats the member initializer of a constructor as a single long line regardless of the length of this line.
For long lines clang-format should introduce line breaks in some sensible way.

**Comment by tijyojwad** [comment]
@ohadmo this should be a good starter task. @ahehn-nv mentioned that some initialized lists in cuda aligner are being formatted into a single line after running `make format`. I believe the file is one of the aligner global files (either Myers global or hirschberg or ukkonen). The ideal formatting would.put the different member initializer lists on different lines

**Comment by vellamike** [comment]
closed by #197
