### ISSUE TITLE
[cudaaligner] FormattedAlignment should include `|` and `x` symbols

### ISSUE THREAD

**Issue by vellamike** [clara-genomics/ClaraGenomicsAnalysis#141]
`FormattedAlignment` in cudaaligner returns aligned strings in the following format:

```
ACCGTCA
ACGC--A
```

This would be preferable:

```
ACCGTCA
||xx  |
ACGC--A
```

**Comment by tijyojwad** [comment]
@ohadmo This task is to update the function in the `Alignment` object in `cudaaligner` that returns a formatted alignment string pair. The ask is to format the strings in a way that shows the match, mismatch and insertion/deletion more clearly.

Some background here - https://users.ugent.be/~avierstr/principles/aligning.html
