### ISSUE TITLE
Add CIGAR alignments to cudamapper using cudaaligner

### ISSUE THREAD

**Issue by vellamike** [clara-genomics/ClaraGenomicsAnalysis#150]
* Add optional `cigar` attribute to `Overlap` objects.
* Add `-a` flag to cudamapper for the option of computing alignments
* Once overlapping is complete, alignments can be completed in batches using cudaaligner.
* If alignments are computed, they should be added to the `PAF` file (the relevant modification needs to be performed in the `print_paf` function).

**Comment by tijyojwad** [comment]
Added necessary column to PAF in https://github.com/clara-genomics/ClaraGenomicsAnalysis/pull/189

**Comment by tijyojwad** [comment]
Assigning to @ahehn-nv for #189
