### ISSUE TITLE
Use pip to install pyclaragenomics instead of setup.py

### ISSUE THREAD

**Issue by tijyojwad** [clara-genomics/ClaraGenomicsAnalysis#153]
There are several benefits to using `pip` to install custom packages instead of running `setup.py` directly. A good summary can be found here - https://stackoverflow.com/questions/15724093/difference-between-python-setup-py-install-and-pip-install/15731459

**Comment by tijyojwad** [comment]
@ohadmo here's another task which should be quick to check. Right now we use `python setup.py` directly to install. Would be great to see if we can install using pip as it takes care of upgrading older versions too

**Comment by ohadmo** [comment]
Following the talk on 4.11:
Create an installation shell script which:
- Checks python version and pip.
- Receives cmake build folder location as an argument.
- pip Install pyclaragenomics/requirments.txt file in it.
- install 'pyclaragenomics' from a folder (without packaging first).
