### ISSUE TITLE
Graph representation in python and serialization methods

### ISSUE THREAD

**Issue by jonn-smith** [clara-genomics/ClaraGenomicsAnalysis#157]
The python bindings are very helpful to perform alignments and consensus calls, but there currently isn't a good way to work with the resulting graph structures in python.  The structures are available in C++, but there are some nuances to them.  It would be nice if there were some examples (with documentation) of working with the resulting graphs in C++ and some bindings (or a new interface) to work with them in python as well.

It would also be helpful if there were a method that can be called after performing an alignment or consensus call that would serialize the graph (in DOT or some similar format) so it can be easily inspected / visualized after creation.

**Comment by tijyojwad** [comment]
Hi @jonn-smith ! Thanks a lot for filing this request, and glad to hear you're finding the APIs useful!

Currently our graph structures are all kept in CUDA memory, but we can certainly expose them in C++ and python data structures for further analysis and visualization. 

Do you have a sense of the priority on this request? That'll help us schedule work for this feature appropriately.

Thanks!

**Comment by jonn-smith** [comment]
@tijyojwad It would be pretty helpful for the work I'm doing, so I would like it to be a high priority (but I also don't want to derail your development cycles).

I was toying with the idea of doing some of it myself (either using the MSA sequences to rebuild the graph without edge weights or exposing the `GraphDetails` with a getter and then updating the python bindings), but I started to get concerned that it might be a rabbit hole for me since I'm not familiar with the details of the code.

**Comment by tijyojwad** [comment]
Sounds good @jonn-smith . We'll prioritize this request, and I will get back to you with an ETA in a day or so

**Comment by jonn-smith** [comment]
Great!  Sounds good!

**Comment by tijyojwad** [comment]
Hi @jonn-smith , apologies for the late response. We're dealing with some urgent items right now for an upcoming release, and it's seems difficult to get this request into that release which is slated for next week. I think however that we can get this feature in sometime around the 4th week of October (maybe soon if things go well next week :) ).

**Comment by tijyojwad** [comment]
Hi @jonn-smith - just wanted to update you that we started working on a graph serialization for cudapoa in https://github.com/clara-genomics/ClaraGenomicsAnalysis/pull/209. The C++ graph should be up in a day or two, the python bindings will follow immediately after. Apologies for getting to this so late!

**Comment by jonn-smith** [comment]
@tijyojwad Sounds good!  No prob!  Glad to hear that it'll be in soon!

**Comment by tijyojwad** [comment]
Hi @jonn-smith - it took a while for the changes to go in, but now we expose the graph structure from cudapoa in a networkx graph (changes pushed in #227 ). Can you try it out and close the issue if fits your needs?

**Comment by jonn-smith** [comment]
@tijyojwad Cool - I'll take a look at it.  I may not get to it this week, but I'll let you know when I have tried it out.  Thanks!

**Comment by tijyojwad** [comment]
@jonn-smith Per our testing this feature is working. I'm closing this issue as of now. If you face any problems when using it, please file a bug with CGA
