### ISSUE TITLE
python build fails when Doxygen not present

### ISSUE THREAD

**Issue by cjw85** [clara-genomics/ClaraGenomicsAnalysis#162]
When setup.py first runs `cmake` it is noted that:

```-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE)
-- Doxygen not found. Doc gen disabled.
```

but the subsequent `cmake --build ... docs install` call fails.

**Comment by tijyojwad** [comment]
Hi @cjw85 - fixed the issue with https://github.com/clara-genomics/ClaraGenomicsAnalysis/pull/163 but merged into our current release development branch (`dev-v0.3.0`). Could you try that branch out and confirm if the changes work for you now?

**Comment by tijyojwad** [comment]
Closing (fix verified here - https://github.com/clara-genomics/ClaraGenomicsAnalysis/pull/163#issuecomment-537049630 )
