### ISSUE TITLE
Remove Ubuntu dependency

### ISSUE THREAD

**Issue by kellyrowland** [clara-genomics/ClaraGenomicsAnalysis#193]
On Linux distributions which aren't Ubuntu or CentOS, building the source code fails with the 'unrecognized distro' fatal error. This error occurs in Packaging, which is not relevant to building the rest of the code to use on a given machine and should not block this.

**Comment by tijyojwad** [comment]
Thanks for filing this issue @kellyrowland . Will look into fixing this ASAP.

**Comment by tijyojwad** [comment]
@kellyrowland fix merged in the dev-v0.4.0 branch. Can you validate if the changes work for you?

Can you also let us know which OS you were running on?
