### ISSUE TITLE
[cudamapper] cub cmake setup

### ISSUE THREAD

**Issue by tijyojwad** [clara-genomics/ClaraGenomicsAnalysis#218]
The usage of `cub` in CMake can be improved by making the `cub` folder an interface target (similar to what we have to the `utils` folder).

**Comment by mimaric** [comment]
@tijyojwad is this still valid?

**Comment by tijyojwad** [comment]
Don't think so. Current setup in cmake/3rdparty.cmake looks good as it imports `cub` as a library. Closing.
