### ISSUE TITLE
[cudaaligner] Mismatch in formatted alignment when running sample

### ISSUE THREAD

**Issue by ohadmo** [clara-genomics/ClaraGenomicsAnalysis#220]
Steps to reproduce:
- Fetch pull request #219 changes. 
- Build CGA and run 'sample_cudaaligner -p'
- The pairing string does not correspond to the query & target strings.

@tijyojwad reported that when setting query length to 50 and target length to 60 in the sample, then alignments come out fine. But when increasing those to 100 and 110 respectively, then the issue arises.

**Comment by tijyojwad** [comment]
Hotfix merged into master and dev branches, and offending changes reverted. Closing since the multi-warp myers (which caused the bug) is being dropped in favor of banded implementation which will make up for the performance impact of the reversion.
