### ISSUE TITLE
[cudamapper] optimize overlapper

### ISSUE THREAD

**Issue by tijyojwad** [clara-genomics/ClaraGenomicsAnalysis#222]
Optimize the overlapper in cudamapper to keep anchors generated from matcher in GPU memory when finding overlaps. Also port the overlap detection algorithm to GPU completely.

**Comment by mimaric** [comment]
@tijyojwad @akkamesh 
Overlapper is far for optimized, but the things this issue describes have been done, right?

**Comment by akkamesh** [comment]
> @tijyojwad @akkamesh
> Overlapper is far for optimized, but the things this issue describes have been done, right?

Yes, the issue described here is complete. Closing it.
