### ISSUE TITLE
[cudamapper] data race in cudamapper

### ISSUE THREAD

**Issue by ahehn-nv** [clara-genomics/ClaraGenomicsAnalysis#272]
There is a data race in cudamapper's main.cu, which may result in an out-of-bound read

When the atomic variable `ranges_idx` is `query_target_ranges.size()-1`, two (or more) threads may enter the loop
https://github.com/clara-genomics/ClaraGenomicsAnalysis/blob/67ff96c80bc7fcce589c2af83d93e73bfc7015f4/cudamapper/src/main.cu#L306
before one of the threads increments `ranges_idx` in next line:
https://github.com/clara-genomics/ClaraGenomicsAnalysis/blob/67ff96c80bc7fcce589c2af83d93e73bfc7015f4/cudamapper/src/main.cu#L308
For the other thread(s) entering the loop, this will result in a `range_idx` value >= `query_target_ranges.size()` and result in an out-of-bound memory access in line
https://github.com/clara-genomics/ClaraGenomicsAnalysis/blob/67ff96c80bc7fcce589c2af83d93e73bfc7015f4/cudamapper/src/main.cu#L312

**Comment by mimaric** [comment]
Are you sure about this? Let's say `query_target_ranges.size() == 10` and `ranges_idx == 9`. First thread does `int range_idx = ranges_idx.fetch_add(1)` after which `range_idx (thread_1) == 9, ranges_idx = 10`. Thread 2 then does the same after which `range_idx (thread_1) == 9, range_idx (thread_2) == 10, ranges_idx = 11`. Thread 1 will enter `if (range_idx < query_target_ranges.size())`, thread 2 won't. Or I'm missing something?

**Comment by ahehn-nv** [comment]
Did I overlook line
https://github.com/clara-genomics/ClaraGenomicsAnalysis/blob/67ff96c80bc7fcce589c2af83d93e73bfc7015f4/cudamapper/src/main.cu#L310
Has it always been there? :confused:
Anyhow, apparently there's no problem then.

**Comment by vellamike** [comment]
The line  `(range_idx < query_target_ranges.size())` is kind of non-intuitive but I couldn't think of a better way to solve this race condition without it.

**Comment by ahehn-nv** [comment]
I think that line is perfectly fine. I got confused by this line:
https://github.com/clara-genomics/ClaraGenomicsAnalysis/blob/67ff96c80bc7fcce589c2af83d93e73bfc7015f4/cudamapper/src/main.cu#L306

I would have expected something along these lines:
```
while(1)
{
  int range_idx = ranges_idx.fetch_add(1);
  if(range_idx >= query_target_ranges.size())
    break;
  // otherwise do stuff
}
```
But I was just a victim of my own anticipation.
