### ISSUE TITLE
About BM_SingleBatchAlignment

### ISSUE THREAD

**Issue by mahmoodn** [clara-genomics/ClaraGenomicsAnalysis#289]
May I know more information about `BM_SingleBatchAlignment<AlignerGlobalUkkonen>/256/4096`? What are those 2 numbers?

**Comment by tijyojwad** [comment]
Hi @mahmoodn , apologies for the late response.

In the run above, 256 corresponds to the batch size, i.e. number of alignments sent to the GPU to be processed together, and 4096 refers to the size of the alignment strings, i e. Aligning a string of 4096 elements to another string 4096 elements

**Comment by mahmoodn** [comment]
Thanks for the reply.
So that means 256 batches are sent to GPU and each batch contains 2 strings with length of 4096. Does that mean GPU receives two strings each containing 1M symbols? or 256 batches are sent and GPU align them sequentially? or maybe batch number is divided by the SM numbers for better efficiency.

**Comment by mahmoodn** [comment]
Also, for the POA benchmarks I see

BM_SingleBatchTest/1024
BM_MultiBatchTest/16

The first one makes sense. One batch with two strings each containing 1K symbols.
However, the multi-batch test is not clear. Does 16 means the number of batches? What are the string lengths then?

**Comment by tijyojwad** [comment]
Apologies @mahmoodn somehow I missed the notification for this issue!

> So that means 256 batches are sent to GPU and each batch contains 2 strings with length of 4096. Does that mean GPU receives two strings each containing 1M symbols? or 256 batches are sent and GPU align them sequentially? or maybe batch number is divided by the SM numbers for better efficiency.

256 batches of 4096x4096 strings are sent in one go to the GPU to align. All the queries and all the targets are stored together in to large input vectors, so yes two 1M char long strings are sent to the GPU and the kernel indexes into the relevant portions of the array. Each warp takes care of one alignment, and they're scheduled in parallel.

> The first one makes sense. One batch with two strings each containing 1K symbols.
However, the multi-batch test is not clear. Does 16 means the number of batches? What are the string lengths then?

Multi-batch is the case where we launch multiple batches (each with fewer strings) to run POA on the GPU. e.g. Going from 1 batch w/ 1024 POA groups -> 4 batches with 256 POA groups. Dividing the problem into multiple batches is helpful in overlapping compute with memory transfers (by using CUDA streams), and typically leads to better end to end performance.
