### ISSUE TITLE
[cudamapper] CIGAR integration

### ISSUE THREAD

**Issue by mimaric** [clara-genomics/ClaraGenomicsAnalysis#321]
CIGAR part uses a custom stream and does not use `device_buffer`/preallocating allocator.

Revisit that implementation, identify necessary changes and implement them

See:
#307 
#313 
#316 
#318 
#320

**Comment by tijyojwad** [comment]
Adding @ahehn-nv to assignee as well to investigate using pre-allocated allocator in cuda aligner

**Comment by ahehn-nv** [comment]
@tijyojwad I think this is done. Can we close it?

**Comment by tijyojwad** [comment]
Yes :). Thanks @ahehn-nv !
