### ISSUE TITLE
Can not find cudaaligner executable after compiling

### ISSUE THREAD

**Issue by estebanpw** [clara-genomics/ClaraGenomicsAnalysis#339]
Hello,

I want to run `cudaaligner` but after compiling successfully I am unable to find the executable.
For instance, the `cudamapper` tool is found in the `../ClaraGenomicsAnalysis/build/install/bin` folder. However I have ran `find ../ClaraGenomicsAnalysis -name "cudaaligner" -executable -type f` and nothing shows. Can you please help? Thank you.
BTW: I am not running as sudo as I have no permissions

**Comment by tijyojwad** [comment]
Hi @estebanpw , `cudaaligner` (like `cudapoa`) is currently available as a library with C++/Python APIs for performing sequence to sequence global alignment.

The C++ header file for the `cudaaligner` API is installed to `install/include/cudaaligner/`, and the relevant library is in `install/lib`. A sample usage of it can be found in https://github.com/clara-genomics/ClaraGenomicsAnalysis/blob/dev-v0.5.0/cudaaligner/samples/sample_cudaaligner.cpp

The Python API is built as part of `pyclaragenomics` and a sample for it is available in https://github.com/clara-genomics/ClaraGenomicsAnalysis/blob/dev-v0.5.0/pyclaragenomics/samples/sample_cudaaligner

Can you tell us more about how you would use a `cudaaligner` binary? We can consider extending the SDK to have one if that's useful

**Comment by estebanpw** [comment]
Hello @tijyojwad 
I was interested in testing the performance of `cudaaligner` with different sized sequences, since I am working on sequence alignment myself and particularly using GPUs now. That said, a binary could be useful as a tool for general-purpose alignments, such as the emboss needle, but on the GPU. 
Anyways, by looking at the sample file you linked I get another question: is `cudaalign` a pairwise sequence aligner or a MSA? In the help it says that it is the first, but there is also an option to print the MSA or consensus. Is this MSA done progressively?
Thanks!

**Comment by tijyojwad** [comment]
Hi @estebanpw Thanks for the explanation! It should be pretty straightforward for us to use cudaaligner API and build a pairwise global alignment tool that's GPU accelerated. I filed #345 to track that feature request.

As for MSA, you just found a bug in our documentation :). We support MSA generation through the `cudapoa` API but not the `cudaaligner` API.

**Comment by estebanpw** [comment]
Happy to help :-) 
I will be watching issue #345

**Comment by tijyojwad** [comment]
Sounds good! Closing this issue for now and tracking the feature request in #345 .
