### ISSUE TITLE
Path Missing CMakeLists.txt

### ISSUE THREAD

**Issue by vaibhaw1994kumar** [clara-genomics/ClaraGenomicsAnalysis#40]
I tried to install Claragenomics in ubuntu 18.04 using command cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=install,but I'm getting this error
The source directory /home/vaibhavcurl/ClaraGenomicsAnalysis-master/3rdparty/bioparser
does not contain a CMakeLists.txt file.
The source directory

    /home/vaibhavcurl/ClaraGenomicsAnalysis-master/3rdparty/spdlog

  does not contain a CMakeLists.txt file.

**Comment by tijyojwad** [comment]
@vaibhaw1994kumar what might have happened is the submodule for `spdlog` didn't get initialized. Ca

**Comment by vaibhaw1994kumar** [comment]
okk...fine..it's resolved..thanks

**Comment by estebanpw** [comment]
This happened to me as well on release 0.4.4. Running `git submodule update --init --recursive` solved it.
