### ISSUE TITLE
Kernel Error:: Node count exceeded maximum nodes per window

### ISSUE THREAD

**Issue by SamStudio8** [clara-genomics/ClaraGenomicsAnalysis#47]
Observed this error on my `stderr` while running `racon-gpu`, not sure if related to #45? It's [raised by the code here](https://github.com/clara-genomics/ClaraGenomicsAnalysis/blob/master/cudapoa/src/cudapoa_batch.cpp#L204).

**Comment by SamStudio8** [comment]
This limit [seems to be a predefined constant](https://github.com/clara-genomics/ClaraGenomicsAnalysis/blob/master/cudapoa/src/cudapoa_kernels.cuh#L29). I guess the size of the graph we have is just a bit big! I could increase this threshold myself, but don't know what the ramifications of that might be.

**Comment by SamStudio8** [comment]
Ah, I see this is actually an error that you've also referenced in #46!

**Comment by SamStudio8** [comment]
Having tested #46, it seems the conditions are related.

**Comment by tijyojwad** [comment]
@SamStudio8 forgot to mention that the fix for this was merged to master for both ClaraGenomicsAnalysis and racon. Can we close this issue if it works for you?

**Comment by SamStudio8** [comment]
Yes I think we can close this!
