### ISSUE TITLE
Unable to clone

### ISSUE THREAD

**Issue by mahmoodn** [clara-genomics/ClaraGenomicsAnalysis#53]
Hi, 
The clone command fails with access right error.
```
$ git clone --recursive git@github.com:clara-genomics/ClaraGenomicsAnalysis.git
Cloning into 'ClaraGenomicsAnalysis'...
The authenticity of host 'github.com (140.82.114.3)' can't be established.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'github.com,140.82.114.3' (RSA) to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```
Any thought?

**Comment by SamStudio8** [comment]
Hi @mahmoodn, you need to [add an SSH key to your Github account](https://help.github.com/en/articles/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent) for the machine you are trying to clone the repository to. Alternative you can clone using https instead of ssh:

```git clone --recursive https://github.com/clara-genomics/ClaraGenomicsAnalysis.git```

**Comment by vellamike** [comment]
Thanks @SamStudio8 !

**Comment by mahmoodn** [comment]
Thanks. I used the second method as I am more familiar with that. I supposed that there are some reasons for that github account method.
