### ISSUE TITLE
About singlebatch 

### ISSUE THREAD

**Issue by mahmoodn** [clara-genomics/ClaraGenomicsAnalysis#54]
I went to `build/install/benchmarks/cudapoa/` and when I run `singlebatch`, I get the following output

```
$ ./singlebatch
2019-07-29 13:14:25
Running ./singlebatch
Run on (16 X 3600 MHz CPU s)
CPU Caches:
  L1 Data 32K (x8)
  L1 Instruction 64K (x8)
  L2 Unified 512K (x8)
  L3 Unified 8192K (x2)
Load Average: 0.33, 0.15, 0.16
***WARNING*** CPU scaling is enabled, the benchmark real time measurements may be noisy and will incur extra overhead.
------------------------------------------------------------------
Benchmark                        Time             CPU   Iterations
------------------------------------------------------------------
BM_SingleBatchTest/1          1594 ms         1593 ms            1
BM_SingleBatchTest/4          2429 ms         2427 ms            1
BM_SingleBatchTest/16         2687 ms         2685 ms            1
BM_SingleBatchTest/64         3231 ms         3228 ms            1
BM_SingleBatchTest/256        8233 ms         8225 ms            1
terminate called after throwing an instance of 'std::runtime_error'
  what():  GPU Error:: out of memory /home/mahmood/cactus/cl/ClaraGenomicsAnalysis/cudapoa/src/allocate_block.cpp 46
Aborted (core dumped)
```

I would like to test a specific batch size and not variable sizes. It seems that singlebatch is a binary file. Any idea for that?

**Comment by vellamike** [comment]
Hi @mahmoodn - could you provide information about your system (especially your GPU)?

**Comment by mahmoodn** [comment]
Quadro M2000 with 4GB of memory.
I know that it will eventually runs out of memory. However, I want to analyze a specific batch size, e.g. 128.

**Comment by ahehn-nv** [comment]
Unfortunately, you cannot choose the size for `singlebatch` freely at the moment, but only select one of the predefined values, e.g.
```
./singlebatch --benchmark_filter=BM_SingleBatchTest/64
```

**Comment by mahmoodn** [comment]
Thant is also good. 
Is there any other examples (such as getting started) and not benchmarks? I see limited guides about Clara.
Moreover, is google benchmark something different than `benchmarks/cudapoa/`?

**Comment by mahmoodn** [comment]
Also, may I know what are the sequences in the cudapoa/singlebatch benchmarks? What does it calculate and then measure the time?

**Comment by tijyojwad** [comment]
Hi @mahmoodn 
Google benchmarks is the framework we use for writing microbenchmarks. Benchmarks/cudapoa is the folder with the benchmark binaries for cudapoa.
Right now the only guides we have are the documentation in doxygen (`make docs install`), the benchmarking code in `single-batch.hpp` or `multi-batch.hpp` and our integration into `racon`. We have plans to write sample programs, but haven't released ant. My guess is those would be easier to parse than the benchmark code. We can prioritize those for the next release.

The sequences used are set of groups (or windows) we extracted from a racon run of long read data from e coli. The source file is under `cudapoa/data`.

Our next release of cudapoa (v0.2 slatwd for mis August) will have better memory management, and will only use available GPU memory to run the compute. So you won't see out of memory problems like you noticed here.

**Comment by mahmoodn** [comment]
Thanks for explanation.
It seems that batch size of 128 is not used in the benchmark. I tried to understand single-batch.hpp and main.cpp to see how can I do that. Is that possible?

**Comment by ahehn-nv** [comment]
Hi @mahmoodn,
https://github.com/clara-genomics/ClaraGenomicsAnalysis/blob/20f0ed107fdad90e66609ae053c5fb0521613b93/cudapoa/benchmarks/single-batch/main.cpp#L35 sets up the benchmark cases. Line 37,
```
->RangeMultiplier(4)
```
says that it will create the benchmark sizes by multiplying the size of the previous benchmark size by  4. So it jumps from 64 to 256. If you change this to 2, it will create benchmarks for more batch sizes, including 128.

**Comment by mahmoodn** [comment]
Thank you very much.
